[project]
site_name = "Module 5 - Data Engineering Product Development"
dev_addr = "0.0.0.0:8000"

nav = [
  {"Overview" = "index.md"},
  {"Agenda" = [
    {"Day 1" = "agenda/day1.md"},
    {"Day 2" = "agenda/day2.md"},
    {"Day 3" = "agenda/day3.md"},
  ]},
  {"Day 1 - Foundation & Setup" = [
    {"Library Pipeline Scenario" = "day1/scenario.md"},
    {"Library Pipeline Sample Data" = "day1/sample-data.md"},
    {"Your Mission" = "day1/your-mission.md"},
    {"Creating Architecture Diagrams" = "day1/create-diagram.md"},
    {"Design your pipeline architecture" = "day1/design-pipeline.md"},
    {"Writeup Architecture Decision Record" = "day1/adr.md"},
    {"Create a GitHub repository" = "day1/create-repo.md"},
    {"Introduce GitHub Projects" = "day1/create-project.md"},
    {"Set up Kanban Board" = "day1/project-tasks.md"},
    {"Local development" = "day1/clone-repo.md"},
    {"Create local development env" = "day1/dev-environment.md"},
    {"Write first Python code" = "day1/write-code.md"},
  ]},
  {"Day 2 - Build & Test Python Package" = [
    {"🌅 Welcome to Day 2 of DE5 Module 5" = "labs/21-setup.md"},
    {"🖥️ VM Setup + LOD Setup" = "labs/22-python-setup.md"},
    {"Run Commands to see Status" = "labs/23-yardstick.md"},
    {"Explain function - Data Ingestion" = "day2/ingestion.md"},
    {"Run Commands to see Status" = "labs/23-yardstick.md"},
    {"Explain function - Data Cleaning" = "day2/cleaning.md"},
    {"Write function - Data Cleaning" = "day2/cleaning-enhancements.md"},
    {"Validation Function" = "day2/validation.md"},
    {"Python Testing" = "day2/python-testing.md"},
    {"Write unit tests" = "day2/cleaning-tests.md"},
    {"Python Test Coverage" = "day2/coverage.md"},
    {"Achieve 70% Coverage" = "day2/coverage-goal.md"},
    {"Fix All Linting Issues" = "day2/linting-fixes.md"},
    {"Explain Linting" = "day2/linting.md"},
    {"Run Commands to see Status" = "labs/23-yardstick.md"},
  ]},
  {"Day 3 - Automation & Integration" = [
    {"GitHub Actions" = "day3/github-actions.md"},
    {"GitHub Actions ~ Trigger Workflow" = "day3/github-workflow.md"},
    {"Pull Request Workflow" = "day3/github-branch.md"},
    {"Complete Your Own PR Workflow" = "day3/pull-request.md"},
    {"01 Create Fabric Lakehouse" = "labs/01-lakehouse.md"},
    {"Run pipeline in MS Fabric" = "day3/fabric-integration.md"},
    {"Create Gold Layer Table" = "day3/fabric-gold-layer.md"},
  ]},
  {"Resources" = "resources.md"},
]


[project.theme]
variant = "classic"

features = [
  "announce.dismiss",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "toc.integrate",

  #"content.action.edit",
  #"content.action.view",
  #"header.autohide",
  #"navigation.expand",
  #"navigation.footer",
  #"navigation.instant",
  #"navigation.instant.prefetch",
  #"navigation.instant.progress",
  #"navigation.path",
  #"navigation.sections",
  #"navigation.tabs",
  #"navigation.tabs.sticky",
  #"navigation.top",
  #"navigation.tracking",
  #"search.highlight",
  #"toc.follow",
]
    
[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
    
[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
    
[project.theme.icon]
logo = "material/database"
    
